name: code_scan_listener
description: Listen for any hardware barcode scanner without any manufacturer SDK
version: 0.2.0
homepage: https://github.com/utamori/code_scan_listener

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  checks: ^0.2.2
  clock: ^1.1.1
  collection: ^1.17.1
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
