name: barcode_listener
description: Listen for any hardware barcode(or qrcode) scanner without any manufacturer SDK. Forked and maintained by SeanKD.
version: 0.4.2
homepage: https://github.com/SeanKD/barcode_listener
topics: [barcode, qrcode, scanner, listener, hardware-key-board]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0

dev_dependencies:
  checks: ^0.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
